spring.application.name=saec
# ====================================
# MySql
# ====================================
spring.datasource.url=jdbc:mysql://localhost:3306/SAEC?useSLL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=1CFUN@M[2024].
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ====================================
# MongoDB
# ====================================
spring.data.mongodb.uri=mongodb://localhost:27017/SAEC_DB

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/doc/swagger-ui.html
springdoc.paths-to-match=/api/**

server.port=8080